name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: server  # Specify the subdirectory

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json  # Specify the path to package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./server  # Set working directory for this step

      - name: Build the project
        run: npm run build --if-present
        working-directory: ./server  # Set working directory for this step

      - name: Run tests
        run: npm test
        working-directory: ./server  # Set working directory for this step
